### ISSUE TITLE
Mobile vs. desktop difference.

### ISSUE THREAD

**Issue by tmr83** [lennyhans/7kaa-static-site#20]
On my mobile, the 7kfans website shows 2.15.4p1 as available for download while on my laptop, it shows 2.15.5 as available.

**Comment by tmr83** [comment]
So I found out that I hadn't whitelisted 7kfans.com yet on my mobile. Now it is displaying correctly even if I tell Noscript to block javascript on 7kfans.com. I am not sure how that works... I am using some version of Firefox from Fdroid, so you can ignore and close this issue if it is nothing.

**Comment by lennyhans** [comment]
I can not reproduce the issue, can you explain a little bit what did you do to make it happen?

**Comment by tmr83** [comment]
It's probably nothing then. I just wanted to help somehow.
