### ISSUE TITLE
Small updates to sync website

### ISSUE THREAD

**Issue by the3dfxdude** [lennyhans/7kaa-static-site#24]
Hello lennyhans,

I have created a git repo on sourceforge with some of my local changes. Please pull in these changes. This is where I will be publishing the live website.
https://sourceforge.net/p/skfans/7kfans-web/

If you are ok with the news cards I will go live with the change to the website. They look ok to me. It might be good to add a title, name and date on the individual news articles automatically if anyone links to them. I don't know for sure.

**Comment by lennyhans** [comment]
Done, I have pulled in the changes, Indeed you were right if you point to 1 news article, it looks weird, I will check that, but anyways it is hard to land to the specific article right now. 
Thanks for pointing that out!

**Comment by lennyhans** [comment]
This is ready to work with the last update @the3dfxdude ! :smile: 
- https://github.com/lennyhans/7kaa-static-site/pull/25
![image](https://github.com/lennyhans/7kaa-static-site/assets/22986072/94e154f8-53cd-4879-9525-52fcc90efd4d)

**Comment by the3dfxdude** [comment]
Hello Lenny,

The community.md file was deleted. That means we will not have a working link to view the articles.

-Jesse

**Comment by lennyhans** [comment]
Hi!, you are right, I skipped the file :facepalm:, restored!

**Comment by the3dfxdude** [comment]
Can you please restore the file to the correct location too? It should be /community.html.

-Jesse

**Comment by lennyhans** [comment]
I think that was not made the ideal way, so I propose a more hierarchical one, as it will be a folder it should be the index on that level, so you can reach to it as `<base>/community/` and `<base>/community/index.html` not `<base>/community.html`, because in the first it is natural to navigate from there to your desired guide and not in another place. 
Maybe I've should explain that before making the change. 
I hope it makes sense.

**Comment by the3dfxdude** [comment]
Hi Lenny,

What I should also say, the navigation link at the top is still broken because it wasn't updated with the file rename. It doesn't matter if it's /community.html or /community/. However, I do prefer the former organization, because then going to /community/ gives an auto generated index, which now we will not have because it is replaced by a static index page.

-Jesse

**Comment by lennyhans** [comment]
Well, about that I want to auto-generate the community index, just like the download and news, so seems to be the right step, I will fix the link, that for some reason for me just works even with the `community.html`, when the time comes I will delete that index in favor of the auto-generated. 
Thanks for the feedback!
